const fs = require('fs');
const path = require('path');

const packageJson = require('../package.json');
const version = packageJson.version;

const versionFilePath = path.join(__dirname, '../src/app/version.ts');

const content = `// This file is generated by scripts/write-version.js
export const version = '${version}';
`;

fs.writeFileSync(versionFilePath, content, { encoding: 'utf8' });

console.log(`Version ${version} written to ${versionFilePath}`);
